name: chat

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PICO_BOARD: pico-w

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            git build-essential cmake ninja-build gcc-arm-none-eabi \
            libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib \
            libusb-1.0-0-dev python3-pip


      - name: Clone upstream MicroPython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git micropython
          cd micropython
          git submodule update --init

      - name: Enable USB-HID & Bluetooth in mpconfigport.h
        working-directory: micropython/ports/rp2
        run: |
          # Backup in case you need to roll back
          cp mpconfigport.h mpconfigport.h.bak

          # Insert HID + Bluetooth support immediately after the USB_CDC define
          sed -i '/#define MICROPY_HW_USB_CDC[[:space:]]*(1)/a\
            // Enable USB HID (keyboard + mouse)\
            #define MICROPY_HW_USB_HID (1)\
            \
            // Enable the Bluetooth API (requires CYW4343x/NimBLE support)\
            #define MICROPY_PY_BLUETOOTH (1)\
            #define MICROPY_BLUETOOTH_NIMBLE (1)' mpconfigport.h

          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ build-essential libnewlib-arm-none-eabi
      
      - name: Build UF2 (release) with CMake
        working-directory: micropython/ports/rp2
        run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DPICO_SDK_FETCH_FROM_GIT=ON \
            -DPICO_BOARD=pico_w \
            -DMICROPY_PY_BLUETOOTH=1 \
            -DMICROPY_BLUETOOTH_NIMBLE=1 \
            -DCMAKE_C_FLAGS="-Wno-error=stringop-overflow -Wno-error=maybe-uninitialized -mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_CXX_FLAGS="-mcpu=cortex-m0plus -mthumb"
          cmake --build .

      - name: Collect firmware.uf2
        run: |
          mkdir -p artifacts
          cp micropython/ports/rp2/build/firmware.uf2 artifacts/pico2w-custom.uf2
          
      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico2w-custom.uf2
          path: artifacts/pico2w-custom.uf2
