name: Build Custom MicroPython UF2 for Raspberry Pi Pico W

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          gcc-arm-none-eabi \
          libnewlib-dev \
          cmake \
          ninja-build \
          python3-dev \
          libffi-dev \
          zlib1g-dev \
          mtools

    - name: Set up Pico SDK
      run: |
        export PICO_SDK_FETCH_FROM_GIT=1
        export PICO_SDK_PATH=${GITHUB_WORKSPACE}/pico-sdk
        git clone --depth 1 -b master https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init

    - name: Set up MicroPython repository
      run: |
        export MICROPY_PATH=${GITHUB_WORKSPACE}/micropython
        git clone --depth 1 -b v1.23.0 https://github.com/micropython/micropython.git
        cd ${MICROPY_PATH}
        git submodule update --init port/rp2

    - name: Create build directory
      run: |
        mkdir -p build-pico_w
        cd build-pico_w

    - name: Configure build (USB HID + Bluetooth/Wireless)
      run: |
        export PICO_BOARD=pico_w
        export PICO_TOOLCHAIN_PATH=/usr/bin
        cmake -G Ninja \
          -DPICO_SDK_PATH=${PICO_SDK_PATH} \
          -DCMAKE_BUILD_TYPE=Release \
          -D MICROPY_PY_USB=1 \
          -D MICROPY_PY_USB_HID=1 \
          -D MICROPY_BLUETOOTH=1 \
          ../../ports/rp2

    - name: Build MicroPython
      run: |
        ninja -v

    - name: Extract UF2 file
      run: |
        cd ../ports/rp2/build-${PICO_BOARD}/firmware
        cp micropython.uf2 micropython-${PICO_BOARD}-usbhid-bt.uf2

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v3
      with:
        name: micropython-uf2
        path: micropython-${PICO_BOARD}-usbhid-bt.uf2
